version: '3'
name: cardano-market-tracker
networks:
  tracker_network:
    driver: bridge
volumes:
  redpanda-1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./kafka/kafkaV21/data
  redpanda-2:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./kafka/kafkaV22/data
  redpanda-3:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./kafka/kafkaV23/data
services:
  redpanda-1:
    command:
      - redpanda
      - start
      - --kafka-addr internal://redpanda-1:9092,external://redpanda-1:19092
      - --advertise-kafka-addr internal://redpanda-1:9092,external://redpanda-1:19092
      - --pandaproxy-addr internal://redpanda-1:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda-1:8082,external://redpanda-1:18082
      - --schema-registry-addr internal://redpanda-1:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda-1:33145
      - --advertise-rpc-addr redpanda-1:33145
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '1'
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.12
    container_name: redpanda-1
    volumes:
      - redpanda-1:/var/lib/redpanda/data
    networks:
      - tracker_network
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
  redpanda-2:
    command:
      - redpanda
      - start
      - --kafka-addr internal://redpanda-2:9092,external://redpanda-2:29092
      - --advertise-kafka-addr internal://redpanda-2:9092,external://redpanda-2:29092
      - --pandaproxy-addr internal://redpanda-2:8082,external://0.0.0.0:28082
      - --advertise-pandaproxy-addr internal://redpanda-2:8082,external://redpanda-2:28082
      - --schema-registry-addr internal://redpanda-2:8081,external://0.0.0.0:28081
      - --rpc-addr redpanda-2:33145
      - --advertise-rpc-addr redpanda-2:33145
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '2'
      - --seeds redpanda-1:33145
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.12
    container_name: redpanda-2
    volumes:
      - redpanda-2:/var/lib/redpanda/data
    networks:
      - tracker_network
    ports:
      - 28081:28081
      - 28082:28082
      - 29092:29092
      - 29644:9644
    depends_on:
      - redpanda-1
  redpanda-3:
    command:
      - redpanda
      - start
      - --kafka-addr internal://redpanda-3:9092,external://redpanda-3:39092
      - --advertise-kafka-addr internal://redpanda-3:9092,external://redpanda-3:39092
      - --pandaproxy-addr internal://redpanda-3:8082,external://0.0.0.0:38082
      - --advertise-pandaproxy-addr internal://redpanda-3:8082,external://redpanda-3:38082
      - --schema-registry-addr internal://redpanda-3:8081,external://0.0.0.0:38081
      - --rpc-addr redpanda-3:33145
      - --advertise-rpc-addr redpanda-3:33145
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '3'
      - --seeds redpanda-1:33145
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.12
    container_name: redpanda-3
    volumes:
      - redpanda-3:/var/lib/redpanda/data
    networks:
      - tracker_network
    ports:
      - 38081:38081
      - 38082:38082
      - 39092:39092
      - 39644:9644
    depends_on:
      - redpanda-1
  console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v2.3.1
    networks:
      - tracker_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda-1:9092","redpanda-2:9092","redpanda-3:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda-1:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda-1:9644"]
    ports:
      - 8080:8080
    depends_on:
      - redpanda-1
  cardano-market-tracker:
    image: clarkteddyswap/cardano-markets-tracker
    container_name: cardano-market-tracker
    environment:
      - KAFKA_BROKERS="redpanda-1:19092"
      - START_SLOT=31541004
      - START_HASH="898157caf22b78e8757419f5a5869aaacb691fbdcee7d6d7b74e5c71172dd610"
      - CARDANO_NODE_SOCKET_PATH="/ipc/node.socket"
    volumes:
      - ./config:/config
      - ./scripts:/scripts
      - /tmp:/ipc
    networks:
      - tracker_network
    depends_on:
      - redpanda-1
      - redpanda-2
      - redpanda-3