version: '3'

services:
  zooV2:
    image: zookeeper:3.4.9
    hostname: zooV2
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
    volumes:
      - "./kafka/zooV2/data:/data:rw"
      - "./kafka/zooV2/datalog:/datalog:rw"
    networks:
      - kafka-network
  kafkaV21:
    image: confluentinc/cp-kafka:5.3.0
    hostname: kafkaV21
    links:
      - zooV2
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_BROKER_ID: 1
      KAFKA_REPLICATION_FACTOR: 3
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_ZOOKEEPER_CONNECT: "zooV2:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafkaV21:9092,CONNECTIONS_FROM_HOST://192.168.50.25:19091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - 19091:19091
    volumes:
      - "./kafka/kafkaV21/data:/var/lib/kafka/data:rw"
    networks:
      - kafka-network
  kafkaV22:
    image: confluentinc/cp-kafka:5.3.0
    hostname: kafkaV22
    links:
      - zooV2
    environment:
      KAFKA_REPLICATION_FACTOR: 3
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "zooV2:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafkaV22:9092,CONNECTIONS_FROM_HOST://192.168.50.25:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - 19092:19092
    volumes:
      - "./kafka/kafkaV22/data:/var/lib/kafka/data:rw"
    networks:
      - kafka-network
  kafkaV23:
    image: confluentinc/cp-kafka:5.3.0
    hostname: kafkaV23
    links:
      - zooV2
    environment:
      KAFKA_REPLICATION_FACTOR: 3
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafkaV23:9092,CONNECTIONS_FROM_HOST://192.168.50.25:19093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: "zooV2:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - 19093:19093
    volumes:
      - "./kafka/kafkaV23/data:/var/lib/kafka/data:rw"
    networks:
      - kafka-network
  kafka-ui:
      image: provectuslabs/kafka-ui
      container_name: kafka-ui
      environment:
        - DYNAMIC_CONFIG_ENABLED=true
      ports:
        - "8080:8080"
      depends_on:
        - kafkaV21
        - kafkaV22
        - kafkaV23
      networks:
        - kafka-network

networks:
  kafka-network:
    driver: bridge